"""One-off: pull the six problem illustrations out of the design files into src/data/illustrations.ts.

Kept in the repo so the extraction is reproducible. Edits requested after the handoff are applied below.
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "design-handoff" / "source"

def svgs(name):
    s = (SRC / name).read_text()
    out = {}
    for i in range(1, 7):
        m = re.search(r'<sc-if value="\{\{(?:p\.)?is%d\}\}"[^>]*>\s*(<svg.*?</svg>)\s*</sc-if>' % i, s, flags=re.S)
        svg = re.sub(r'\s*\n\s*', '', m.group(1))
        out[i] = svg
    return out

mobile, desktop = svgs("home-mobile.dc.html"), svgs("home-desktop.dc.html")

# 01: proof now talks about laundry liquids at pH 9+, so move the marker from pH 10 to pH 9.
mobile[1] = (mobile[1]
    .replace('laundry powder at 10 or higher', 'laundry liquid at 9 or higher')
    .replace('x1="450" y1="44" x2="450"', 'x1="409" y1="44" x2="409"')
    .replace('<text x="390" y="32">POWDER 10+</text>', '<text x="350" y="32">LIQUID 9+</text>'))
desktop[1] = (desktop[1]
    .replace('laundry powder at 10 or higher', 'laundry liquid at 9 or higher')
    .replace('x1="450" y1="44" x2="450"', 'x1="409" y1="44" x2="409"')
    .replace('<circle cx="450" cy="44"', '<circle cx="409" cy="44"')
    .replace('<text x="380" y="32"', '<text x="339" y="32"')
    .replace('LAUNDRY POWDER · 10+', 'LAUNDRY LIQUID · 9+'))

# 03: "Where we test" marker removed from the copy.
desktop[3] = re.sub(r'<rect x="220" y="156"[^>]*></rect>', '', desktop[3])
desktop[3] = re.sub(r'<text[^>]*>← WHERE WE TEST: 200 TO 300</text>', '', desktop[3])

# No uppercase anywhere on the site: illustration labels in sentence case.
CONTINUATIONS = {"SCALE": "scale", "NOT TO SCALE": "not to scale", "MG/L": "mg/L"}

def sentence(text):
    if text in CONTINUATIONS:
        return CONTINUATIONS[text]
    t = text.lower()
    t = re.sub(r"\bbis\b", "BIS", t).replace("mg/l", "mg/L")
    t = re.sub(r"\bok\b", "OK", t)
    return t[0].upper() + t[1:] if t[:1].isalpha() else t

def sentence_case_svg(svg):
    return re.sub(r"(<text[^>]*>)([^<]+)(</text>)", lambda m: m.group(1) + sentence(m.group(2)) + m.group(3), svg)

for d in (mobile, desktop):
    for k, v in d.items():
        v = sentence_case_svg(v)
        v = v.replace(' font-family="sans-serif"', '')
        v = re.sub(r'<svg ', '<svg focusable="false" ', v, count=1)
        d[k] = v

checks = [('Liquid 9+' in mobile[1]), ('Laundry liquid · 9+' in desktop[1]), ('WHERE WE TEST' not in desktop[3]), ('x1="450"' not in desktop[1])]
assert all(checks), checks

out = ROOT / "src" / "data" / "illustrations.ts"
out.write_text(
    "// Generated by scripts/extract-illustrations.py from design-handoff/source. Do not edit by hand.\n"
    f"export const ILLUS_MOBILE: Record<number, string> = {json.dumps(mobile, ensure_ascii=False, indent=2)};\n\n"
    f"export const ILLUS_DESKTOP: Record<number, string> = {json.dumps(desktop, ensure_ascii=False, indent=2)};\n"
)
print("wrote", out, {k: len(v) for k, v in desktop.items()})
